spring:
application:
name: inventory-service

datasource:
url: jdbc:postgresql://localhost:5432/inventory_db
username: postgres
password: postgres
driver-class-name: org.postgresql.Driver

jpa:
hibernate:
ddl-auto: none
show-sql: true
properties:
hibernate:
format_sql: true

liquibase:
change-log: classpath:db/changelog/db.changelog-master.yaml

# gRPC ????????????
grpc:
server:
port: 9090  # ???? ??? gRPC (REST API ????? ?? 8080)
enable-keep-alive: true
keep-alive-time: 30s
keep-alive-timeout: 5s
permit-keep-alive-without-calls: true

server:
port: 8080  # REST API ????

logging:
level:
org.example.inventoryservice: DEBUG
io.grpc: INFO