--liquibase formatted sql

--changeset admin:1
CREATE TABLE IF NOT EXISTS products
(
id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
name VARCHAR(64) NOT NULL,
quantity NUMERIC(10, 2) NOT NULL,
price DOUBLE PRECISION NOT NULL,
sale NUMERIC(10, 2) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
--changeset admin:2
CREATE INDEX idx_products_name ON products(name);

--changeset admin:3
COMMENT ON TABLE products IS 'Product inventory table';
COMMENT ON COLUMN products.id IS 'Unique product identifier';
COMMENT ON COLUMN products.name IS 'Product name';
COMMENT ON COLUMN products.quantity IS 'Available quantity in stock';
COMMENT ON COLUMN products.price IS 'Product price before discount';
COMMENT ON COLUMN products.sale IS 'Discount percentage (0-100)';
COMMENT ON COLUMN products.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN products.updated_at IS 'Record last update timestamp';