--liquibase formatted sql

--changeset admin:1
CREATE TABLE IF NOT EXISTS users
(
id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
username   VARCHAR(50)  NOT NULL UNIQUE,
password   VARCHAR(255) NOT NULL,
email      VARCHAR(100) NOT NULL UNIQUE,
role       VARCHAR(20)  NOT NULL DEFAULT 'USER',
created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL
);

--changeset admin:2
CREATE INDEX idx_users_username ON users(username);

--changeset admin:3
CREATE INDEX idx_users_email ON users(email);

--changeset admin:4
COMMENT ON TABLE users IS 'User accounts table';
COMMENT ON COLUMN users.id IS 'Unique user identifier';
COMMENT ON COLUMN users.username IS 'Unique username for authentication';
COMMENT ON COLUMN users.password IS 'BCrypt hashed password';
COMMENT ON COLUMN users.email IS 'User email address';
COMMENT ON COLUMN users.role IS 'User role (USER, ADMIN)';
COMMENT ON COLUMN users.created_at IS 'Account creation timestamp';
