--liquibase formatted sql

--changeset admin:1
CREATE TABLE IF NOT EXISTS orders
(
    id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id          BIGINT           NOT NULL,
    total_price      DOUBLE PRECISION NOT NULL,
    status           VARCHAR(20)      NOT NULL DEFAULT 'PENDING',
    items_json       JSONB            NOT NULL,
    delivery_address VARCHAR(500),
    created_at       TIMESTAMP        DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

--changeset admin:2
CREATE INDEX idx_orders_user_id ON orders(user_id);

--changeset admin:3
CREATE INDEX idx_orders_status ON orders(status);

--changeset admin:4
CREATE INDEX idx_orders_created_at ON orders(created_at);

--changeset admin:5
COMMENT ON TABLE orders IS 'Customer orders table';
COMMENT ON COLUMN orders.id IS 'Unique order identifier';
COMMENT ON COLUMN orders.user_id IS 'Reference to user who created the order';
COMMENT ON COLUMN orders.total_price IS 'Total order price after discounts';
COMMENT ON COLUMN orders.status IS 'Order status (PENDING, SENT_TO_KAFKA, COMPLETED, FAILED)';
COMMENT ON COLUMN orders.items_json IS 'Order items in JSON format';
COMMENT ON COLUMN orders.delivery_address IS 'Delivery address for the order';
COMMENT ON COLUMN orders.created_at IS 'Order creation timestamp';
COMMENT ON COLUMN orders.updated_at IS 'Order last update timestamp';
